Проект 10 спринта, попытка 1
JabaHott/java-filmorate pull request #11
Opened 2024-04-03 19:50 UTC by JabaHott

Для инфо:
Взял новй ноут и накатил себе линукс, немного не понял, но комит мог пойти с др аккаунта, тут муть какая-то в идее

2024-04-06 06:49 UTC, YazykovMikhail commented
В комментариях к коммитам лучше писать конкертно что делал, "[Проект 10 спринта, попытка 1]" - такие сообщения не информтивны)

2024-04-06 07:15 UTC, YazykovMikhail requested changes

2024-04-06 07:15 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.debug("Сохранен пользователь : {}", film.toString());
toString() - делать не нужно, он и так будет применен

2024-04-06 07:15 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Map<Long, Film> getAll() {
Стоит возаращть список, а не Map
Список всех фильмов

2024-04-06 07:15 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Map<Long, Film> getAll() {
Поправь и для User

2024-04-06 07:15 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Set<Long> getLikes(Long userId) {
Метод не используется

2024-04-06 07:15 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if ((film.getName().isBlank() || film.getName().equals(null))) {
film.getName().equals(null)) - вот так null не стоит проверять ,потому что это не сработает, если там и правда булет Null то будет NPE
 вот эту проверку if ((film.getName().isBlank() || film.getName().equals(null))) { стоит переделать на:
      `  if (( film.getName() == null || film.getName().isBlank())) {`

сначала проверять на null и только потом применять уже методы, иначе опятьже елси будет имя null то при вызвое .isBlank() будет NPE

2024-04-06 07:15 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if ((film.getName().isBlank() || film.getName().equals(null))) {
И в целом большинство проверок тут не нужно, потому что они уже слеоаны через аннотации, оставь тут только те , что нельзя сделать через аннотации
Касается и User

2024-04-06 07:15 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private FilmStorage filmStorage;
не забывай про final
 поправь везде

2024-04-06 07:15 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void validate(User user) {
обычно приватные методы пишутся в самом низу, потому что сначала все смотрят публичные
Опусти его ниже публичных

2024-04-06 07:15 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    Map<Long, Film> filmMap = new HashMap<>();
private final
лучше не использовать в названии переменных их тип, назови как нибудь
films или filmsStorage

2024-04-06 07:15 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    Map<Long, Film> filmMap = new HashMap<>();
Аналогично для User

2024-04-06 07:15 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Film create(Film film) {
Лучше вот так:
    public Film create(Film film) {
        Long id = ++filmIdCounter;
        film.setId(id);
        filmMap.put(id, film);
        return film;
    }
 и соответсвенно  private Long filmIdCounter = 0L; начать с 0
 Это убирает сразу две проблемы:
 1) Каждый метод сам для себя делает id, а не для будущего использования
 2) Сощдается id в локальную переменную, а потом уже используется там где нужно, ведь в таком коде:
```
         film.setId(filmIdCounter);
        filmMap.put(filmIdCounter, film);
```
между этими двуми вызовами кто то может увилить счетчик id, ведь запросы вызваеются одновременно много и получится рассинхрон

2024-04-06 07:15 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Film create(Film film) {
Поправь и для User

2024-04-06 07:15 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Map<Long, Film> getAll() {
Стоит возращать спиок, думаю уже понял

2024-04-11 16:53 UTC, JabaHott commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  public class UserController implements UserControllerInterface {
добрый вечер!
Интерфейсы контроллеров используются для групповой валидации поля id

2024-04-13 08:18 UTC, YazykovMikhail approved these changes

2024-04-13 09:21 UTC, merged